apiVersion: v1
kind: Service
metadata:
  name: ${JOB_NAME}
  labels:
    app: ${JOB_NAME}
spec:
  ports:
    - port: 80
  selector:
    app: ${JOB_NAME}
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ${JOB_NAME}
spec:
  selector:
    matchLabels:
      app: ${JOB_NAME}
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ${JOB_NAME}
        build_number: ${BUILD_NUMBER}
        role: rolling-update
    spec:
      containers:
      - name: ${JOB_NAME}
        image: master01:9443/nginx:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
